# Generated by Django 5.2 on 2025-04-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='descriptoin',
            field=models.TextField(blank=True),
        ),
    ]
