# Generated by Django 5.2 on 2025-04-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_works_descriptoin'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='works',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
