# Generated by Django 5.2 on 2025-04-25 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_works_is_completed_works_is_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='works',
            old_name='is_completed',
            new_name='delete',
        ),
        migrations.RemoveField(
            model_name='works',
            name='is_deleted',
        ),
    ]
