# Generated by Django 5.2 on 2025-04-25 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_rename_is_completed_works_delete_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='works',
            old_name='delete',
            new_name='is_deleted',
        ),
    ]
